[exp]
file = "drone_race_env.py"  # env file name
deploy_file = "real_race_env.py"
seed = 42

[controller]
# file = "attitude_race.py"
file = "attitude_rl_race.py"

[deploy]
[[deploy.drones]]
id = 10
channel = 100
drone_model = "cf21B_500"    # cf2x_L250, cf2x_P250, cf2x_T500, cf21B_500.
takeoff_pos = [-1.5, 0.75, 0.01]  # Takeoff position [x, y, z] in meters

[env]
physics = "first_principles" # "first_principles", "so_rpy_rotor_drag"
control = "attitude"         # "state", "attitude", "force_torque", "rotor_vel", "rl_state"(only deploy)
drone_model = "cf21B_500"    # cf2x_L250, cf2x_P250, cf2x_T500, cf21B_500
freq = 50                    # Environment frequency, in Hz.
sim_freq = 500               # Simulation frequency, in Hz.
state_freq = 50              # State estimation frequency, in Hz.
attitude_freq = 500          # Controller frequency, in Hz.
force_torque_freq = 500      # Force/torque frequency, in Hz.
sensor_range = 10            # Range at which the exact location of gates and obstacles become visible to the drone. Objects that are not in the drone's sensor range report their nominal position.
reset_rotor = true           # Whether to reset rotor velocities on env.reset()


[env.track]

# Tall gates: 1.195m height. Short gates: 0.695m height. Height is measured from the ground to the center of the gate.
# Gates are square. Gates are 0.72m wide (outer dimensions of the frame) with a 0.4m wide opening.
[[env.track.gates]]
pos = [0.5 , 0.25, 0.7]
rpy = [0.0, 0.0, -0.78]
[[env.track.gates]]
pos = [1.05, 0.75, 1.2]
rpy = [0.0, 0.0, 2.35]
[[env.track.gates]]
pos = [-1.0, -0.25, 0.7]
rpy = [0.0, 0.0, 3.14]
[[env.track.gates]]
pos = [0.0, -0.75, 1.2]
rpy = [0.0, 0.0, 0.0]

# Obstacle height: 1.52m + reflective marker on top. Height is measured from the ground to the top of the obstacle.
# Obstacles are cylinders with a diameter of 0.03m.
[[env.track.obstacles]]
pos = [0.0, 0.75, 1.55]
[[env.track.obstacles]]
pos = [1.0, 0.25, 1.55]
[[env.track.obstacles]]
pos = [-1.5, -0.25, 1.55]
[[env.track.obstacles]]
pos = [-0.5, -0.75, 1.55]

[[env.track.drones]]
pos = [-1.5, 0.75, 0.1]
rpy = [0.0, 0.0, 0.0]
vel = [0, 0, 0]
ang_vel = [0, 0, 0]

# [env.disturbances.action]
# fn = "normal"
# scale = 0.001

# [env.disturbances.dynamics]
# fn = "uniform"
# [env.disturbances.dynamics.kwargs]
# minval = [-0.1, -0.1, -0.1]
# maxval = [0.1, 0.1, 0.1]

# [env.randomizations.drone_pos]
# fn = "uniform"
# [env.randomizations.drone_pos.kwargs]
# minval = [-0.1, -0.1, 0.0]
# maxval = [0.1, 0.1, 0.02]

# [env.randomizations.drone_rpy]
# fn = "uniform"
# [env.randomizations.drone_rpy.kwargs]
# minval = [-0.1, -0.1, -0.1]
# maxval = [0.1, 0.1, 0.1]

# [env.randomizations.drone_mass]
# fn = "uniform"
# [env.randomizations.drone_mass.kwargs]
# minval = -0.005
# maxval = 0.005

# [env.randomizations.drone_inertia]
# fn = "uniform"
# [env.randomizations.drone_inertia.kwargs]
# minval = [-0.000001, -0.000001, -0.000001]
# maxval = [0.000001, 0.000001, 0.000001]

# [env.randomizations.gate_pos]
# fn = "uniform"
# [env.randomizations.gate_pos.kwargs]
# minval = [-0.15, -0.15, -0.1]
# maxval = [0.15, 0.15, 0.1]

# [env.randomizations.gate_rpy]
# fn = "uniform"
# [env.randomizations.gate_rpy.kwargs]
# minval = [-0.05, -0.1, -0.2]
# maxval = [0.05, 0.1, 0.2]

# [env.randomizations.obstacle_pos]
# fn = "uniform"
# [env.randomizations.obstacle_pos.kwargs]
# minval = [-0.15, -0.15, -0.05]
# maxval = [0.15, 0.15, 0.05]
