[controller]
file = "attitude_rl.py"

[deploy]

[[deploy.drones]]
id = 52
channel = 80
drone_model = "cf21B_500"  # Model of the drone, i.e., cf2x_L250, cf2x_P250, cf2x_T500, cf21B_500. For this course, we use cf21B_500


[sim]
# Physics options:
# "first_principles": first_principles (physics based) model
# "so_rpy": Simplified identified model.
# "so_rpy_rotor": Simplified identified model with rotor dynamics.
# "so_rpy_rotor_drag": Simplified identified model with rotor dynamics and drag.
physics = "so_rpy_rotor_drag"
drone_model = "cf21B_500"                        # Model of the drone, i.e., cf2x_L250, cf2x_P250, cf2x_T500, cf21B_500. For this course, we use cf21B_500
camera_view = [5.0, 180.0, -25.0, 0.0, 0.0, 0.0] # Camera view [distance, azimuth, elevation, lookat_x, lookat_y, lookat_z]
freq = 500                                        # Simulation frequency, in Hz
attitude_freq = 500                               # Controller frequency, in Hz. This frequency is used to simulate the onboard controller, NOT for the environment's step function
render = false                                       # Enable/disable PyBullet's GUI

[env]
id = "DroneDefault-v0"   # "DroneEnv-v0" for single races, "MultiDroneRacing-v0" for multi-drone races. Each environment also implements a vector-environment for faster training
seed = 42               # Either "random" for a random behavior or an integer for reproducibility
freq = 50               # Frequency of the environment's step function, in Hz
sensor_range = 0.7      # Range at which the exact location of gates and obstacles become visible to the drone. Objects that are not in the drone's sensor range report their nominal position.
control_mode = "attitude"  # Control mode of the environment. Can be either "state" or "attitude"

[env.disturbances.action]
fn = "normal"
scale = 0.001

[env.disturbances.dynamics]
fn = "uniform"
[env.disturbances.dynamics.kwargs]
minval = [-0.1, -0.1, -0.1]
maxval = [0.1, 0.1, 0.1]
